version: '3.8'
services:
        nginx:
                image: nginx:1.19.5-alpine
                container_name: acg_nginx
                restart: always
                volumes:
                        - ./static:/app/static
                        - ./uploads:/app/uploads
                        - ./etc/acg.conf:/etc/nginx/conf.d/acg.conf
                        - ./etc/nginx.conf:/etc/nginx/nginx.conf
                ports:
                        - "80:80"
        mongo:
                image: mongo:4.4.2
                container_name: acg_db
                restart: always
                volumes:
                        - ./mongodata:/data/db
                ports:
                        - "27017:27017"
